[ADD] jwt provider, filter 추가 및 Security, Mvc configuration 일부 추가
semtleWebGroup/youtube-clone-Backend pull request #24
Opened 2023-04-07 18:01 UTC by YeaChan05

# 변경 유형

- [x] 기능 추가
- [ ] 성능 개선 ( 리팩토링 )
- [ ] 오류 수정
- [ ] Test Case 추가
- [ ] 기타 (document, 환경설정, CI/CD )

# 변경 내용
- jwt provider, filter 추가
- config 조정

# 참조 자료
- Closes #23

2023-04-08 01:56 UTC, Onji-K requested changes
고쳐야할 부분이 몇군데 있어서 리뷰 남겨 놓았습니다.

2023-04-08 01:56 UTC, Onji-K commented on src/main/java/com/semtleWebGroup/youtubeclone/global/config/WebMvcConfig.java
> +                PageableLimits limits = methodParameter.getParameterAnnotation(PageableLimits.class);
import com.semtleWebGroup.youtubeclone.global.security.PageableLimits;
여기서 임포트하는데 파일이 없는거 같은데 한번 확인해주세요

2023-04-08 01:56 UTC, Onji-K commented on src/main/java/com/semtleWebGroup/youtubeclone/global/config/WebSecurityConfig.java
> +@Configuration
이것들 말고 @EnableWebSecurity 붙여야하지 않나요? 확실하지 않는데, 한번 확인해주세요
그리고 WebSecurityConfigurerAdapter는 Deprecated 라서 새로운 방식으로 쓰는게 나을 거 같네요(필수는 아님)

2023-04-08 01:56 UTC, Onji-K commented on src/main/java/com/semtleWebGroup/youtubeclone/global/config/WebSecurityConfig.java
> +    }
https://github.com/spring-projects/spring-security/blob/5.4.x/config/src/main/java/org/springframework/security/config/annotation/web/configuration/WebSecurityConfigurerAdapter.java#L250

추상 메서드가 아닌데 구지 오버라이드 할 필요가 있나요? 한번 확인해주세요

2023-04-08 01:56 UTC, Onji-K commented on src/main/java/com/semtleWebGroup/youtubeclone/global/config/WebSecurityConfig.java
> +}
good!!

2023-04-08 01:56 UTC, Onji-K commented on src/main/java/com/semtleWebGroup/youtubeclone/global/security/jwt/JwtAuthenticationFilter.java
> +}
good

2023-04-08 01:56 UTC, Onji-K commented on src/main/java/com/semtleWebGroup/youtubeclone/global/security/jwt/JwtTokenProvider.java
> +
위 둘다 환경변수로 빼는게 어떨까요?

2023-04-08 01:56 UTC, Onji-K commented on src/main/java/com/semtleWebGroup/youtubeclone/global/security/jwt/JwtTokenProvider.java
> +    // tocken값 가져오기
typo : token

2023-04-08 01:56 UTC, Onji-K commented on src/test/java/com/semtleWebGroup/youtubeclone/global/security/jwt/JwtAuthenticationFilterTest.java
> +    }
@Autowired인데 mock을 사용하는게 좀 이상하지 않나요? <- 확실치 않은 다른분들 의견

이게 mock 테스트 인지 통합테스트인지 섞여있는거 같습니다.

2023-04-08 01:56 UTC, Onji-K commented on src/test/java/com/semtleWebGroup/youtubeclone/global/security/jwt/JwtAuthenticationFilterTest.java
> +    }
이거 혹시 항상 실패하는 테스트 아닌가요? token을 secret key 넣어서 만든게 아니라 그냥 dummy로 만든거라 validate 해봤자 항상 false 되지 않나요?

그리고 테스트코드 보충해야할거 같습니다.
- 올바른 토큰 전달시
- 아무 토큰도 없을시
- 잘못된 토큰 전달시
- 만료된 토큰 전달시

어떤 값이 기대되는지

이정도는 있어야될거 같네요

2023-04-08 01:56 UTC, Onji-K commented on src/test/java/com/semtleWebGroup/youtubeclone/global/security/jwt/JwtTokenProviderTest.java
> + */
@SpringBootTest 를 붙인 통합 테스트 인지, 목업 테스트인지 섞여있습니다

2023-04-08 01:56 UTC, Onji-K commented on src/test/java/com/semtleWebGroup/youtubeclone/global/security/jwt/JwtTokenProviderTest.java
> +        assertTrue(token.length() > 0);
NotNull 대신 있는지 모르겠는데 NotEmpty같은 거로 하면 좋을 거 같습니다.
그리고 이게 비어있지 않기만 하면 되는게 아니라, key 넣고 풀었을때 제대로 나오는지, 유효 한지, 다 체크되어야 할거 같네요

이 테스트코드는 그냥 아무 값이나 던져주면 다 통과 됩니다

2023-04-08 07:33 UTC, Onji-K commented on src/main/java/com/semtleWebGroup/youtubeclone/global/security/jwt/JwtTokenProvider.java
> +    private final UserDetailsService userDetailsService;
UserDetailsService 구현이 안되있는거 같은데, 어디서 주입받는건가요?

2023-04-08 09:00 UTC, YeaChan05 commented on src/main/java/com/semtleWebGroup/youtubeclone/global/config/WebMvcConfig.java
> +                PageableLimits limits = methodParameter.getParameterAnnotation(PageableLimits.class);
올린줄 알았는데 안올렸었네요 ㅎㅎ,,

2023-04-08 09:49 UTC, YeaChan05 commented on src/main/java/com/semtleWebGroup/youtubeclone/global/config/WebSecurityConfig.java
> +@Configuration
맞네요
어차피 OAuth2ImportSelector쓰려면 @EnableWebSecurity로 정정해야겠네요
수정하겠습니다
그리고 deprecated된 부분은 수정하려고 하면 할수는 있겠네요
추후에 조정 가능하면 수정하는부분으로 염두에 두겠습니다
[https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter](url) 를 참조하였습니다

2023-04-08 09:57 UTC, YeaChan05 commented on src/main/java/com/semtleWebGroup/youtubeclone/global/config/WebSecurityConfig.java
> +    }
확인했습니다
오버라이드 굳이 할 필요는 없어보이네요

2023-04-08 09:58 UTC, YeaChan05 commented on src/main/java/com/semtleWebGroup/youtubeclone/global/security/jwt/JwtTokenProvider.java
> +
어차피 변경할 값들이라 일단은 변수 대입으로 넣어뒀는데 추후에 따로 설정파일에 저장해두겠습니다.

2023-04-08 10:25 UTC, YeaChan05 commented on src/main/java/com/semtleWebGroup/youtubeclone/global/security/jwt/JwtTokenProvider.java
> +    private final UserDetailsService userDetailsService;
package org.springframework.security.core에 있더라고요
[https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/core/userdetails/UserDetailsService.html](url)

2023-04-08 11:38 UTC, YeaChan05 commented on src/main/java/com/semtleWebGroup/youtubeclone/global/security/jwt/JwtTokenProvider.java
> +    private final UserDetailsService userDetailsService;
UserDetailsService 을 customize해야 할거같네요.
이부분도 수정해서 push하겠습니다.

2023-04-09 02:21 UTC, Onji-K approved these changes

2023-04-09 13:23 UTC, hj-language approved these changes

2023-04-10 03:01 UTC, Onji-K requested changes
Pagable 및 코드 수정후 다시 approve 필요

2023-05-07 13:38 UTC, closed without merging