[ADD] video 관련 get/post/patch api 구현
semtleWebGroup/youtube-clone-Backend pull request #28
Opened 2023-04-10 15:35 UTC by hj-language

# 변경 유형

- [X] 기능 추가
- [ ] 성능 개선 ( 리팩토링 )
- [ ] 오류 수정
- [ ] Test Case 추가
- [ ] 기타 (document, 환경설정, CI/CD )

# 변경 내용
- GET /videos/:videoId 구현
- POST /videos/:videoId 구현
- PATCH /videos/:videoId 구현
- 자동으로 수정 시간 업데이트를 위해 시간 엔티티를 빼고, application에 @EnableJpaAuditing 추가
- 추후 POST/PATCH api 응답은 변경 데이터만 보내게끔 간소화 예정
 
# 참조 자료
- api 명세서

Closes #26

2023-04-10 23:34 UTC, Onji-K requested changes

2023-04-10 23:34 UTC, Onji-K commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/video/domain/Video.java
>      @Id
메인 레파지토리랑 버전이 다른거 같은데요. 원본 레파지토리는 video_info로 업데이트 되었는데, pull 안하신거 같습니다

그리고 여기는 video_info 테이블 입니다
Video 테이블은 Video_media 도메인에 있습니다

2023-04-10 23:34 UTC, Onji-K commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/video/domain/Video.java
Db에서 blob 이니까 @Lob 으로 해야하지 않나요

2023-04-10 23:34 UTC, Onji-K commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/video/service/VideoService.java
>  public class VideoService {
여기도 버전이 다른거 같습니다.
원본 레파지토리 한번 확인해주세요.
비디오 미디어 레파지토리에 이미 VideoService가 있어서 빈 주입이 안될겁니다

2023-04-10 23:34 UTC, Onji-K commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/video/service/VideoService.java
> +        String dir = System.getProperty("user.dir") + "\\src\\main\\resources\\webapp\\thumbnails";
Blob으로 db 박는게 편하실 겁니다.
도커 환경으로 하면 컨테이너 안에 주소가 linux / 디렉토리가 되고,
도커 안에는 이 프로젝트 폴더가 전부 없습니다. 컴파일된 jar 파일만 올라갑니다.

더군다나 도커 컨테이너 안에서 저장된 데이터가 유지 되려면, 서버 디렉토리에서 볼륨마운트로 연결을 해야하는데, 이렇게 하려면, 테스트 돌릴때 도커환경에서 디버깅 해야해서 복잡해 집미자.

2023-04-10 23:34 UTC, Onji-K commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/video/service/VideoService.java
> +        File saveFile = new File(dir, thumbImgName);
파일으로 저장한다고 해도, 발생할수 있는 예외들을 전부 처리해줘야 합니다. 적어도 트랜잭션 처리는해야합니다.

Db는 올라가고 파일은 저장하다 예외뜨고 등등

2023-04-10 23:34 UTC, Onji-K commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/video/service/VideoService.java
>      public Video get(Integer id) {
구지 따로 메서드로 뺄 필요가 있는지 모르겠습니다.
빼더라도 private로 하는게 맞지 않을까요? 내부용 메서드라면

2023-04-10 23:34 UTC, Onji-K commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/video/service/VideoService.java
> +    }
트랜잭션 처리가 필요합니다. 셋중 하나에서 예외가 발생하면 나머지는 저장된 상태라 데이터가 뒤죽박죽이 됩니다

2023-04-11 02:51 UTC, hj-language commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/video/domain/Video.java
>      @Id
버전이 많이 다르네요. ㅠㅠ 웹에서는 sync fork 해두고 개발할 때 develop 브랜치를 pull 하지 않았네요. pull 후 다시 진행하여 올리겠습니다.

2023-04-11 02:54 UTC, hj-language commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/video/service/VideoService.java
>      public Video get(Integer id) {
네. 저는 GET /video/:videoId에서도 사용하려고 했는데, 생각해보니 이 api에서는 채널명과 같은 다른 테이블 정보도 필요해서 private로 빼두고 api용 메서드를 하나 더 만들어야 할 것 같아요.

2023-04-11 12:09 UTC, onjik approved these changes

2023-04-14 04:11 UTC, Jeonwoojae approved these changes

2023-05-01 08:48 UTC, hj-language commented
변경된 DB 구조로 다시 구현하기 위해 issue를 닫습니다. new issue #29

2023-05-01 08:48 UTC, closed without merging