Feature/#29 video api
semtleWebGroup/youtube-clone-Backend pull request #30
Opened 2023-05-01 09:03 UTC by hj-language

# 변경 유형
Video CRUD 구현
- [X] 기능 추가
- [ ] 성능 개선 ( 리팩토링 )
- [ ] 오류 수정
- [ ] Test Case 추가
- [ ] 기타 (document, 환경설정, CI/CD )

# 변경 내용
- video create 
  - 썸네일 blob 저장, title 및 description 입력받아 저장
- video view
  - videoInfo, video, channel, videoMedia.qualityList 반환
  - TODO
    - media 관련 - getQualityList(videoId) 메서드 필요 => 가능한 quality liset 반환
    - channel 관련 - 이미지, 구독자 수 받아오는 메서드 필요
- video update
  - title, description만 변경 가능
  - 수정 시 updatedDate 함께 수정
- video delete
  - (임시) video 관련 데이터 삭제 후 videoInfo 반환 - **테스트를 위해 videoMediaRepository 건든 부분이 있음!**
  - TODO
    - 추가로 예외 처리 할 부분 없는지 확인 (현재는 videoInfo가 없으면 error)
    - videoService.delete(videoId) 메서드 필요 => videoMedia, video, videoInfo 등 video에 연관된 entity 및 videoLike 관련 row 모두 제거

# 참조 자료
-

2023-05-02 16:46 UTC, hj-language commented
video 스키마 바뀐 부분 정리하고 media 관련 인터페이스 호출하도록 변경 완료했습니다.

2023-05-03 04:53 UTC, Jeonwoojae commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/video/dto/VideoViewResponse.java
> +        this.isLike = videoLike.isLike(); // ? 왜 getIsLike가 아니라 isLike인지 잘 모르겠음.
lombok의 getter를 사용할 경우 다음과 같이 메소드가 정의됩니다.
- boolean 타입: is 접두사 + 필드 이름 (예: isactive())
- 그 외의 타입: get 접두사 + 필드 이름 (예: getName(), getAge(), getMyField())

2023-05-03 04:59 UTC, Jeonwoojae commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/video/controller/VideoApi.java
> +        Video video = videoService.edit(videoId, dto, blobImg);
controller와 service 간에 객체를 교환할 때 dto를 사용하는 건 어떨까요?

2023-05-03 05:03 UTC, Jeonwoojae commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/video/domain/Video.java
> +    @CreatedDate
CreatedDate와 LastModifiedDate 어노테이션을 사용하면 객체 생성 및 수정시 자동으로 초기화, 업데이트 되는 걸로 알고있습니다

2023-05-03 05:06 UTC, Jeonwoojae approved these changes, later dismissed
리뷰 완료했습니다!

2023-05-03 10:15 UTC, Onji-K requested changes
저 예외 처리 부분은 처리가 필요할 것 같습니다. SQLExcepiton의 경우 저도 확실치 않은데, DataAcessException인가? 로 db관련 예외들이 부모를 두고 있는 걸로 알고 있습니다. 예외를 잡아서 다른 예외로 변환을 하던지, 해야할 것 같습니다.

2023-05-03 10:15 UTC, onjik commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/video/controller/VideoApi.java
> +    ) throws IOException, SQLException {
이 두 예외는 어디서 처리되나요?

2023-05-03 10:15 UTC, onjik commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/video/domain/VideoLike.java
> +    private UUID videoLikeId;
이거는 외부 공개용이 아니라, 구지 uuid로 할 필요가 없을 거 같네요. DB 부분은 좀 논의가 필요해 보입니다

2023-05-03 13:20 UTC, hj-language commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/video/dto/VideoViewResponse.java
> +        this.isLike = videoLike.isLike(); // ? 왜 getIsLike가 아니라 isLike인지 잘 모르겠음.
감사합니다 !! 😄

2023-05-03 13:22 UTC, hj-language commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/video/domain/Video.java
> +    @CreatedDate
LastModifiedDate를 이용하면 조회수 증가로 인해 수정해야 하는 경우에 해당 필드도 변경되어 사용하지 않았습니다.!!

2023-05-03 13:24 UTC, hj-language commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/video/controller/VideoApi.java
> +    ) throws IOException, SQLException {
모든 로직에 대해 예외 처리를 완벽하게 해두진 않았습니다. 로직에 문제가 없다면 예외 처리 방식을 좀 통일해서 처리하려고 합니다.!!

2023-05-03 13:29 UTC, hj-language commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/video/domain/VideoLike.java
> +    private UUID videoLikeId;
그럼 프론트에서 video like에 대한 id를 처리할 부분은 없어보여서 우선 놔두고, 다음 회의 때 논의 후 변경해야 할 필요가 있다면 Long 같은 걸로 변경하겠습니다

2023-05-03 13:29 UTC, hj-language commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/video/controller/VideoApi.java
> +        Video video = videoService.edit(videoId, dto, blobImg);
좋은 것 같습니다. 따로 정의하여 다시 구현해보겠습니다.

2023-05-03 13:31 UTC, onjik commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/video/domain/VideoLike.java
> +    private UUID videoLikeId;
CREATE TABLE IF NOT EXISTS `youtube_clone`.`video_like` (
  `video_like_id` BIGINT(20) NOT NULL,
  `channel_id` BIGINT(20) NOT NULL,
  `video_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`video_like_id`),
  INDEX `fk_video_like_channel1_idx` (`channel_id` ASC) VISIBLE,
  INDEX `fk_video_like_video1_idx` (`video_id` ASC) VISIBLE,
  CONSTRAINT `fk_video_like_channel1`
    FOREIGN KEY (`channel_id`)
    REFERENCES `youtube_clone`.`channel` (`channel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_like_video1`
    FOREIGN KEY (`video_id`)
    REFERENCES `youtube_clone`.`video` (`video_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
sql 상으로 BIGINT여서 long으로 하시면 될 것 같습니다.

2023-05-04 01:21 UTC, Onji-K approved these changes, later dismissed

2023-05-04 15:14 UTC, YeaChan05 approved these changes

2023-05-04 15:15 UTC, Onji-K approved these changes

2023-05-04 15:46 UTC, merged