Feacure/jwt
semtleWebGroup/youtube-clone-Backend pull request #39
Opened 2023-05-07 14:26 UTC by YeaChan05

# 변경 유형

- [x] 기능 추가
- [ ] 성능 개선 ( 리팩토링 )
- [ ] 오류 수정
- [ ] Test Case 추가
- [ ] 기타 (document, 환경설정, CI/CD )

# 변경 내용
- 토큰 발급 및 인증 기능 구현

# 참조 자료
-

2023-05-13 05:05 UTC, Onji-K requested changes

2023-05-13 05:05 UTC, onjik commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/channel/application/ChannelAuthentication.java
> +        return null;
Role 넣어줘야할거 같습니다

2023-05-13 05:05 UTC, onjik commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/channel/application/ChannelAuthentication.java
> +    private boolean isAuthenticated;
이거 초기화가 안되는거 같습니다

2023-05-13 05:05 UTC, onjik commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/channel/domain/Channel.java
> +@NoArgsConstructor(access = AccessLevel.PUBLIC)
이거 왜 퍼블릭으로 바꾸셧나여?

2023-05-13 05:05 UTC, onjik commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/comment/api/CommentApi.java
> +public class CommentApi {
이거 커멘트도 본인이 작성하신건가요?

2023-05-13 05:05 UTC, onjik commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/member/api/MemberAccessDeniedHandler.java
> +        response.sendRedirect("/");
리다이렉트 경로가 홈으로 보내는게 맞나요?

2023-05-13 05:05 UTC, onjik commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/member/api/MemberApi.java
> +    }
이거 auth2 맞나요? 그냥 일반적인 로그인 같은데,
그리고 jwt면, 헤더에 토큰을 전달해야하지 않나요?

2023-05-13 05:05 UTC, onjik commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/member/api/MemberApi.java
> +        }
이거는 누가 호출하는건가요? Auth 맞나요?
그리고, 이메일이 중복되었는지, 중복 가입인지, 각 필드가 잘 들어가 있는지 체크는 어디서 하나요?

2023-05-13 05:05 UTC, onjik commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/member/domain/Member.java
> +@NoArgsConstructor
Protected 필요

2023-05-13 05:05 UTC, onjik commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/member/domain/Member.java
> +        authorities.add(new SimpleGrantedAuthority(role.toString()));
List.of() 로 축약 가능

2023-05-13 05:05 UTC, onjik commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/member/api/MemberApi.java
> +}
로그아웃은 어떻게 하나요

2023-05-13 05:05 UTC, onjik commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/member/domain/Role.java
> +    User("ROLE_USER"), NotVerified("ROLE_NotVerifiedUser");
저 not verified user는 둘 필요가 없습니다.
구글에 role anonymous 검색해보세요

2023-05-13 05:05 UTC, onjik commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/member/dto/SignInRequestDto.java
> +public class SignInRequestDto implements Serializable {
이거 컨트롤러에서 받을때 @Valid 없으면 체크 안됩니다 저 낫널 같은거

2023-05-13 05:05 UTC, onjik commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/member/dto/SignInRequestDto.java
> +    private final String password;
Password 맞나요?
Auth에 비밀번호가 없는거 같은데요

2023-05-13 05:05 UTC, onjik commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/member/domain/Member.java
> +    private String password;
Db에 password 필드가 있나요?

2023-05-13 05:05 UTC, onjik commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/video/dto/VideoEditDto.java
> +        this.channel = channel;
이건 혜진님이 수정하는게 맞습니다

2023-05-13 05:05 UTC, onjik commented on src/main/java/com/semtleWebGroup/youtubeclone/global/config/WebMvcConfig.java
> +                .allowedOrigins("http://localhost:3000")
잘못됬어요

2023-05-13 05:05 UTC, onjik commented on src/main/java/com/semtleWebGroup/youtubeclone/global/config/WebMvcConfig.java
> +                .allowedMethods("GET","POST","DELETE")
이것도 patch도 받아야되고 이거 다 다시 짜야합니다

2023-05-13 05:05 UTC, Onji-K commented on src/main/java/com/semtleWebGroup/youtubeclone/global/security/jwt/JwtAuthenticationFilter.java
> +            throw new Exception("Token is null.");
그냥 exception던지면 안되고 특정해줘야 합니다

2023-05-13 05:05 UTC, Onji-K commented on src/test/java/com/semtleWebGroup/youtubeclone/domain/comment/service/CommentServiceTest.java
> +@Transactional
이거 profile 설정 없어요 , 만약 이거 prod로 성절되어 있으면 운영 db서버 다 drop됩니다

2023-05-15 13:35 UTC, hj-language commented on src/main/java/com/semtleWebGroup/youtubeclone/domain/video/dto/VideoEditDto.java
> +        this.channel = channel;
이 부분 생각해보니 제가 수정한 건데 예찬선배님이 중간에 pull 하셔서 그런가 여기에서도 commit으로 올라간 것 같아요.

2024-02-12 06:18 UTC, closed without merging